drop extension if exists "pg_net";


  create table "public"."clothes" (
    "id" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "category" text,
    "stars" text,
    "tags" text,
    "scores" jsonb,
    "game_id" text
      );


alter table "public"."clothes" enable row level security;


  create table "public"."pending_clothes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
      );



  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "nickname" text,
    "role" text default 'user'::text,
    "quota" integer default 30,
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."profiles" enable row level security;


  create table "public"."stages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "weights" jsonb
      );



  create table "public"."user_quotas" (
    "user_id" uuid not null,
    "free_count" integer default 20
      );


alter table "public"."user_quotas" enable row level security;


  create table "public"."user_wardrobes" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid default gen_random_uuid(),
    "owned_clothes" jsonb
      );


alter table "public"."user_wardrobes" enable row level security;

CREATE UNIQUE INDEX clothes_name_category_unique ON public.clothes USING btree (name, category);

CREATE UNIQUE INDEX clothes_pkey ON public.clothes USING btree (id);

CREATE UNIQUE INDEX pending_clothes_pkey ON public.pending_clothes USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX stages_name_key ON public.stages USING btree (name);

CREATE UNIQUE INDEX stages_pkey ON public.stages USING btree (id);

CREATE UNIQUE INDEX user_quotas_pkey ON public.user_quotas USING btree (user_id);

CREATE UNIQUE INDEX user_wardrobes_pkey ON public.user_wardrobes USING btree (id);

CREATE UNIQUE INDEX user_wardrobes_user_id_key ON public.user_wardrobes USING btree (user_id);

alter table "public"."clothes" add constraint "clothes_pkey" PRIMARY KEY using index "clothes_pkey";

alter table "public"."pending_clothes" add constraint "pending_clothes_pkey" PRIMARY KEY using index "pending_clothes_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."stages" add constraint "stages_pkey" PRIMARY KEY using index "stages_pkey";

alter table "public"."user_quotas" add constraint "user_quotas_pkey" PRIMARY KEY using index "user_quotas_pkey";

alter table "public"."user_wardrobes" add constraint "user_wardrobes_pkey" PRIMARY KEY using index "user_wardrobes_pkey";

alter table "public"."clothes" add constraint "clothes_name_category_unique" UNIQUE using index "clothes_name_category_unique";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."stages" add constraint "stages_name_key" UNIQUE using index "stages_name_key";

alter table "public"."user_quotas" add constraint "user_quotas_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."user_quotas" validate constraint "user_quotas_user_id_fkey";

alter table "public"."user_wardrobes" add constraint "user_wardrobes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."user_wardrobes" validate constraint "user_wardrobes_user_id_fkey";

alter table "public"."user_wardrobes" add constraint "user_wardrobes_user_id_key" UNIQUE using index "user_wardrobes_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.profiles (id, email, nickname, role, quota)
  VALUES (new.id, new.email, split_part(new.email, '@', 1), 'user', 30);
  RETURN new;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user_quota()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.user_quotas (user_id, free_count)
  VALUES (new.id, 30); -- 新用户默认给 20 次
  RETURN new;
END;
$function$
;

grant delete on table "public"."clothes" to "anon";

grant insert on table "public"."clothes" to "anon";

grant references on table "public"."clothes" to "anon";

grant select on table "public"."clothes" to "anon";

grant trigger on table "public"."clothes" to "anon";

grant truncate on table "public"."clothes" to "anon";

grant update on table "public"."clothes" to "anon";

grant delete on table "public"."clothes" to "authenticated";

grant insert on table "public"."clothes" to "authenticated";

grant references on table "public"."clothes" to "authenticated";

grant select on table "public"."clothes" to "authenticated";

grant trigger on table "public"."clothes" to "authenticated";

grant truncate on table "public"."clothes" to "authenticated";

grant update on table "public"."clothes" to "authenticated";

grant delete on table "public"."clothes" to "service_role";

grant insert on table "public"."clothes" to "service_role";

grant references on table "public"."clothes" to "service_role";

grant select on table "public"."clothes" to "service_role";

grant trigger on table "public"."clothes" to "service_role";

grant truncate on table "public"."clothes" to "service_role";

grant update on table "public"."clothes" to "service_role";

grant delete on table "public"."pending_clothes" to "anon";

grant insert on table "public"."pending_clothes" to "anon";

grant references on table "public"."pending_clothes" to "anon";

grant select on table "public"."pending_clothes" to "anon";

grant trigger on table "public"."pending_clothes" to "anon";

grant truncate on table "public"."pending_clothes" to "anon";

grant update on table "public"."pending_clothes" to "anon";

grant delete on table "public"."pending_clothes" to "authenticated";

grant insert on table "public"."pending_clothes" to "authenticated";

grant references on table "public"."pending_clothes" to "authenticated";

grant select on table "public"."pending_clothes" to "authenticated";

grant trigger on table "public"."pending_clothes" to "authenticated";

grant truncate on table "public"."pending_clothes" to "authenticated";

grant update on table "public"."pending_clothes" to "authenticated";

grant delete on table "public"."pending_clothes" to "service_role";

grant insert on table "public"."pending_clothes" to "service_role";

grant references on table "public"."pending_clothes" to "service_role";

grant select on table "public"."pending_clothes" to "service_role";

grant trigger on table "public"."pending_clothes" to "service_role";

grant truncate on table "public"."pending_clothes" to "service_role";

grant update on table "public"."pending_clothes" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."stages" to "anon";

grant insert on table "public"."stages" to "anon";

grant references on table "public"."stages" to "anon";

grant select on table "public"."stages" to "anon";

grant trigger on table "public"."stages" to "anon";

grant truncate on table "public"."stages" to "anon";

grant update on table "public"."stages" to "anon";

grant delete on table "public"."stages" to "authenticated";

grant insert on table "public"."stages" to "authenticated";

grant references on table "public"."stages" to "authenticated";

grant select on table "public"."stages" to "authenticated";

grant trigger on table "public"."stages" to "authenticated";

grant truncate on table "public"."stages" to "authenticated";

grant update on table "public"."stages" to "authenticated";

grant delete on table "public"."stages" to "service_role";

grant insert on table "public"."stages" to "service_role";

grant references on table "public"."stages" to "service_role";

grant select on table "public"."stages" to "service_role";

grant trigger on table "public"."stages" to "service_role";

grant truncate on table "public"."stages" to "service_role";

grant update on table "public"."stages" to "service_role";

grant delete on table "public"."user_quotas" to "anon";

grant insert on table "public"."user_quotas" to "anon";

grant references on table "public"."user_quotas" to "anon";

grant select on table "public"."user_quotas" to "anon";

grant trigger on table "public"."user_quotas" to "anon";

grant truncate on table "public"."user_quotas" to "anon";

grant update on table "public"."user_quotas" to "anon";

grant delete on table "public"."user_quotas" to "authenticated";

grant insert on table "public"."user_quotas" to "authenticated";

grant references on table "public"."user_quotas" to "authenticated";

grant select on table "public"."user_quotas" to "authenticated";

grant trigger on table "public"."user_quotas" to "authenticated";

grant truncate on table "public"."user_quotas" to "authenticated";

grant update on table "public"."user_quotas" to "authenticated";

grant delete on table "public"."user_quotas" to "service_role";

grant insert on table "public"."user_quotas" to "service_role";

grant references on table "public"."user_quotas" to "service_role";

grant select on table "public"."user_quotas" to "service_role";

grant trigger on table "public"."user_quotas" to "service_role";

grant truncate on table "public"."user_quotas" to "service_role";

grant update on table "public"."user_quotas" to "service_role";

grant delete on table "public"."user_wardrobes" to "anon";

grant insert on table "public"."user_wardrobes" to "anon";

grant references on table "public"."user_wardrobes" to "anon";

grant select on table "public"."user_wardrobes" to "anon";

grant trigger on table "public"."user_wardrobes" to "anon";

grant truncate on table "public"."user_wardrobes" to "anon";

grant update on table "public"."user_wardrobes" to "anon";

grant delete on table "public"."user_wardrobes" to "authenticated";

grant insert on table "public"."user_wardrobes" to "authenticated";

grant references on table "public"."user_wardrobes" to "authenticated";

grant select on table "public"."user_wardrobes" to "authenticated";

grant trigger on table "public"."user_wardrobes" to "authenticated";

grant truncate on table "public"."user_wardrobes" to "authenticated";

grant update on table "public"."user_wardrobes" to "authenticated";

grant delete on table "public"."user_wardrobes" to "service_role";

grant insert on table "public"."user_wardrobes" to "service_role";

grant references on table "public"."user_wardrobes" to "service_role";

grant select on table "public"."user_wardrobes" to "service_role";

grant trigger on table "public"."user_wardrobes" to "service_role";

grant truncate on table "public"."user_wardrobes" to "service_role";

grant update on table "public"."user_wardrobes" to "service_role";


  create policy "Enable read access for all users"
  on "public"."clothes"
  as permissive
  for select
  to public
using (true);



  create policy "仅管理员可操作图鉴"
  on "public"."clothes"
  as permissive
  for all
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));



  create policy "管理员权限"
  on "public"."clothes"
  as permissive
  for all
  to authenticated
using ((auth.email() = '2230909994@qq.com'::text))
with check ((auth.email() = '2230909994@qq.com'::text));



  create policy "用户可以查看自己的画像"
  on "public"."profiles"
  as permissive
  for select
  to public
using ((auth.uid() = id));



  create policy "允许用户查看自己的额度"
  on "public"."user_quotas"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));



  create policy "允许用户操作自己的衣柜"
  on "public"."user_wardrobes"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "用户只能操作自己的衣柜"
  on "public"."user_wardrobes"
  as permissive
  for all
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));


CREATE TRIGGER on_auth_user_created_profile AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


